---
name: Build Validation

on:
  pull_request:
    branches: [main]

# for each ref (branch/pr) run just the most recent,
# cancel other pending/running ones
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    # The conditions below define the desired behaviour of the deployment
    # workflow:
    #   1. The workflow must NOT be triggered automatically by an opened
    #     pull request
    #   2. It should be possible to manually trigger the workflow for PRs
    #     originating from forks (using "safe to test" label)
    #   3. The workflow must run when scheduled, pushed (i.e., merge) or
    #     manually triggered
    if: |
      github.event.pull_request.head.repo.full_name == github.repository
      || contains(github.event.pull_request.labels.*.name, 'safe to test')
    permissions:
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of
          # changed files within `super-linter`
          fetch-depth: 0

      - name: Create status check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BUILD_COMMIT=$(git rev-parse HEAD)
          echo "BUILD_COMMIT: ${BUILD_COMMIT}"
          
          curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/microsoft/AzureTRE/check-runs \
          -d '{"name":"ZZZ Deploy PR / Run E2E Tests (Smoke)", "head_sha": "'"$BUILD_COMMIT"'", "status": "completed", "conclusion": "success" }'

      - name: Lint code base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_YAML: true
          VALIDATE_TERRAFORM: true
          RUN_LOCAL: true
          VALIDATE_JAVA: true
          JAVA_FILE_NAME: checkstyle.xml

      - name: Terraform format check
        run: terraform fmt -check -recursive

      # find all terraform folders and run validate to catch
      # configuration errors
      - name: Terraform validation
        run: |
          find . -type d -name 'terraform' -not -path '*cnab*' -print0 \
          | xargs -0 -I{} sh -c 'echo "***** Validating: {} *****"; \
          terraform -chdir={} init -backend=false; terraform -chdir={} validate'
